### ISSUE TITLE
Error while injecting the hooking dll

### ISSUE THREAD

**Issue by LelouchViBri** [AhmedMinegames/MineRootkit#1]
happens when i compile the project myself, the release version works

**Comment by AhmedMinegames** [comment]
make sure to compile program as x64 for x64 programs and same with x86 and if that didn't work then get the last error code using Marshal.GetLastWin32Error() and send it here.

**Comment by LelouchViBri** [comment]
my bad, "MineRootkit" had a default "Any Cpu" which caused this error, switched to x64 and works fine.

**Comment by AhmedMinegames** [comment]
Solved.
