### ISSUE TITLE
Accept Bytes instead of Dll path

### ISSUE THREAD

**Issue by LelouchViBri** [AhmedMinegames/MineRootkit#2]
hello!
The program works really well, just a question since i can't post it anywhere else, how would i convert it to accept bytes instead of a dll path?

`InjectHookingLibrary(byte[] DllInBytes, int PID)`

**Comment by AhmedMinegames** [comment]
you will have to manually map it, cause all the code are doing is it calls LoadLibraryA in the specified process with the dll path and then creates a thread in the specified process and it's start address are LoadLibraryA in order for the program to load it, you will have to emulate what LoadLibraryA do but you will just specify your dll bytes, and you will to fix imports, do reallocation, call DllMain, etc... and it's hard to do that on a managed language.

**Comment by LelouchViBri** [comment]
i see.. is there no other way around without using LoadLibraryA?

**Comment by AhmedMinegames** [comment]
sadly no, there's no winapi which loads dll based on it's bytes.

**Comment by LelouchViBri** [comment]
i tried to find sources of loading dll as bytes , i came to [this](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/309563-c-native-dll-mapper.html). that could work?

**Comment by AhmedMinegames** [comment]
test it.
